services:
  jjy:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    privileged: true
    devices:
      - /dev/mem:/dev/mem
    restart: always
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "/etc/timezone:/etc/timezone:ro"
